In [2]:
import pandas as pd

In [4]:
ingredient_list = ['Texapon SB 3 KC', 'Plantapon ACG 50', 'Plantapon LC 7',
               'Plantacare 818', 'Plantacare 2000',
               'Dehyton MC', 'Dehyton PK 45', 'Dehyton ML', 'Dehyton AB 30',
               'Plantapon Amino SCG-L', 'Plantapon Amino KG-L','Dehyquart A-CA',
               'Luviquat Excellence', 'Dehyquart CC6',
               'Dehyquart CC7 Benz', 'Salcare Super 7', 'Arlypon F', 'Arlypon TT', 'Water']

In [5]:
density_dict = {'Texapon SB 3 KC': 1.128, 'Plantapon ACG 50': 1.147, 'Plantapon LC 7': 1.070,
                'Plantacare 818': 1.104, 'Plantacare 2000': 1.103,
                'Dehyton MC': 1.097, 'Dehyton PK 45': 1.062, 'Dehyton ML': 1.084, 'Dehyton AB 30': 1.031,
                'Plantapon Amino SCG-L': 1.051, 'Plantapon Amino KG-L': 1.028,'Dehyquart A-CA': 0.955,
                'Luviquat Excellence': 1.118, 'Dehyquart CC6': 1.067,
                'Dehyquart CC7 Benz': 1.024, 'Salcare Super 7': 1.121, 'Arlypon F': 0.887, 'Arlypon TT': 0.970, 'Water': 0.998}

In [6]:
DoE = pd.read_csv('DoE_csv/PhD_MasterDataset_OT_initial.csv', index_col=0)
DoE = DoE.loc[:, ~DoE.columns.str.contains('^Unnamed')]  # drop any unnamed columns resulting from formatting issues when saving .xlsx to .csv

# Excel workbook contains mass_fraction, but need to convert this to a volume for the Opentrons to dispense
V_tot = 10000  # ~ require approx. 8-10 mL to submerge the pH probe sufficiently in the pH adjustment step

# Edit these each run :)
start_sample_idx = 7
end_sample_idx = 12

vol_dict = {i: list(round(V_tot*((DoE[i].iloc[start_sample_idx-1:end_sample_idx]*DoE['Sample Density'].iloc[start_sample_idx-1:end_sample_idx])/(100*density_dict[i])))) for i in ingredient_list}

vol_df = pd.DataFrame.from_dict(vol_dict)
#vol_df.index = np.arange(1, len(vol_df) + 1)

vol_df

,Texapon SB 3 KC,Plantapon ACG 50,Plantapon LC 7,Plantacare 818,Plantacare 2000,Dehyton MC,Dehyton PK 45,Dehyton ML,Dehyton AB 30,Plantapon Amino SCG-L,Plantapon Amino KG-L,Dehyquart A-CA,Luviquat Excellence,Dehyquart CC6,Dehyquart CC7 Benz,Salcare Super 7,Arlypon F,Arlypon TT,Water
0,0.0,0.0,651.0,0.0,0.0,0.0,675.0,0.0,0.0,0.0,0.0,0.0,361.0,0.0,0.0,0.0,0.0,344.0,7965.0
1,0.0,0.0,736.0,0.0,0.0,0.0,390.0,0.0,0.0,0.0,0.0,0.0,397.0,0.0,0.0,0.0,0.0,551.0,7926.0
2,0.0,0.0,292.0,0.0,0.0,0.0,702.0,0.0,0.0,0.0,0.0,0.0,252.0,0.0,0.0,0.0,0.0,249.0,8506.0
3,0.0,0.0,565.0,0.0,0.0,0.0,408.0,0.0,0.0,0.0,0.0,0.0,270.0,0.0,0.0,0.0,0.0,218.0,8536.0
4,0.0,0.0,425.0,0.0,0.0,0.0,751.0,0.0,0.0,0.0,0.0,0.0,452.0,0.0,0.0,0.0,0.0,416.0,7955.0
5,0.0,0.0,273.0,0.0,0.0,0.0,684.0,0.0,0.0,0.0,0.0,0.0,514.0,0.0,0.0,0.0,0.0,531.0,7997.0

In [7]:
water_vol = vol_df['Water'].tolist
water_vol

<bound method IndexOpsMixin.tolist of 0    7965.0
1    7926.0
2    8506.0
3    8536.0
4    7955.0
5    7997.0
Name: Water, dtype: float64>